# Production Configuration
# 本番環境設定ファイル

# 基本設定を継承
_base_: default.yaml

# 本番環境固有の設定
conversation:
  max_messages: 200  # 本番では長めに
  reflection_agent_max_count: 5

# ログ設定
logging:
  level: "WARNING"
  directory: "logs/prod"

# 本番設定
production:
  error_recovery: true
  performance_monitoring: true
  rate_limiting: true